$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - .git
  - bun.lockb
  - ./branch_out
  - .changeset
  - drizzle
  - '**/*.svg'
  - .husky
  - package-lock.json
  - package.json
words:
  - asynciterable
  - Tinybird
  - datasource
  - TINYBIRD
  - tinybird
  - chronark
  - supabase
  - plpgsql
  - ossp
  - acst
  - aest
  - akst
  - Anson
  - astro
  - astrojs
  - autodocs
  - autoplay
  - awst
  - Beamer
  - Binni
  - branchname
  - bunx
  - bvaughn
  - Byrom
  - callees
  - cjsx
  - classname
  - clsx
  - cmdk
  - codespace
  - codespaces
  - Colm
  - commitlint
  - commitlintrc
  - compat
  - consts
  - crossorigin
  - ctsx
  - datetime
  - dbaeumer
  - degit
  - dotenv
  - dsznajder
  - Duarte
  - Elsakaan
  - Embla
  - esbenp
  - eslintcache
  - hookform
  - ianvs
  - ixahmedxi
  - jiti
  - jscoverage
  - jspm
  - kohler
  - lockb
  - lucide
  - Malyavko
  - microbundle
  - mikestead
  - minimise
  - Mintlify
  - mjsx
  - monorepoing
  - mtsx
  - neonctl
  - neondatabase
  - nextjs
  - nuxt
  - nzst
  - onwarn
  - optimisations
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - pageview
  - peduarte
  - pids
  - posthog
  - quickstart
  - Ratelimit
  - shadcn
  - sslmode
  - starterkit
  - starterkits
  - stylelint
  - stylelintcache
  - stylesheet
  - superjson
  - tada
  - tailwindcss
  - tamasfe
  - tanstack
  - thollander
  - todos
  - topbar
  - transpiles
  - treeshake
  - trpc
  - tsbuildinfo
  - tsconfigs
  - tseslint
  - tsup
  - Tuite
  - turborepo
  - typecheck
  - typeof
  - typesafe
  - unifiedjs
  - unkey
  - uploadthing
  - vaul
  - viewports
  - vuepress
  - WITA
  - wscript
  - yoav